"""add loyalty points to users

Revision ID: 7f46a9dafe06
Revises: 9f1718be4c1f
Create Date: 2026-06-18 01:06:27.273087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f46a9dafe06'
down_revision: Union[str, Sequence[str], None] = '9f1718be4c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loyalty_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loyalty_points')
    # ### end Alembic commands ###
