"""add warranty and certification to parts

Revision ID: 8a159742eaa7
Revises: bf68ad88a0cf
Create Date: 2026-06-13 09:40:43.091745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a159742eaa7'
down_revision: Union[str, Sequence[str], None] = 'bf68ad88a0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('parts', sa.Column('certification', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'certification')
    op.drop_column('parts', 'warranty_months')
    # ### end Alembic commands ###
