"""add seller approval status

Revision ID: 8d0e0418c2ae
Revises: 9ae27f878d3a
Create Date: 2026-06-20 00:56:48.628675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0e0418c2ae'
down_revision: Union[str, Sequence[str], None] = '9ae27f878d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seller_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seller_status')
    # ### end Alembic commands ###
