"""add seller role and store links

Revision ID: 9ae27f878d3a
Revises: e48925a78f3d
Create Date: 2026-06-18 09:37:37.423852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae27f878d3a'
down_revision: Union[str, Sequence[str], None] = 'e48925a78f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('store_id', sa.UUID(), nullable=True))
    op.add_column('parts', sa.Column('seller_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'parts', 'users', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'parts', 'stores', ['store_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'store_id')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_column('parts', 'seller_id')
    op.drop_column('parts', 'store_id')
    # ### end Alembic commands ###
