"""add delivery phone and email to orders

Revision ID: 9f1718be4c1f
Revises: 276541d6ff8f
Create Date: 2026-06-18 00:54:22.080062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1718be4c1f'
down_revision: Union[str, Sequence[str], None] = '276541d6ff8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_email')
    op.drop_column('orders', 'delivery_phone')
    # ### end Alembic commands ###
