"""add pickup option to orders

Revision ID: e48925a78f3d
Revises: 7f46a9dafe06
Create Date: 2026-06-18 08:53:19.956041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48925a78f3d'
down_revision: Union[str, Sequence[str], None] = '7f46a9dafe06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fulfillment_type', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('pickup_store_id', sa.UUID(), nullable=True))
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'stores', ['pickup_store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('orders', 'pickup_store_id')
    op.drop_column('orders', 'fulfillment_type')
    # ### end Alembic commands ###
